  env:
    node: true

  rules:
    indent: [2, 2]
    quotes: [2, single]
    no-trailing-spaces: 2
    comma-spacing: [2, { before: false, after: true }]
    eqeqeq: [2, always]
    linebreak-style: [2, unix]
    semi: [2, always]
    max-len: [2, 80]

  extends: eslint:recommended
